language: python
python: '2.7'
sudo: required
env:
- PYTHONUNBUFFERED=1
services:
- docker
cache:
  directories:
  - .autoconf
  - $HOME/.m2
install:
- pip install -U pip
script:
- mvn clean pre-integration-test -P withIntegrationTest
- cd /home/travis/build/jenkinsci/gogs-webhook-plugin && mvn failsafe:integration-test -P withIntegrationTest
- find /home/travis/build/jenkinsci/gogs-webhook-plugin -name "test-project.xml"
