language: python
python: '2.7'
sudo: required
env:
- PYTHONUNBUFFERED=1
services:
- docker
before_install:
- sudo apt-get update -qq
install:
- pip install -U pip
script:
- mvn clean pre-integration-test -P withIntegrationTest
- mvn failsafe:integration-test -P withIntegrationTest

